#ifndef MORSEDEFS_H
#define MORSEDEFS_H


#define VERSION_MAJOR 2
#define VERSION_MINOR 0




enum DISPLAY_TYPE { NO_DISPLAY, DISPLAY_BY_CHAR, DISPLAY_BY_WORD };   // how we display in trainer mode
enum random_OPTIONS {OPT_ALL, OPT_ALPHA, OPT_NUM, OPT_PUNCT, OPT_PRO, OPT_ALNUM, OPT_NUMPUNCT, OPT_PUNCTPRO, OPT_ALNUMPUNCT, OPT_NUMPUNCTPRO, OPT_KOCH };
enum PROMPT_TYPE { NO_PROMPT, CODE_ONLY , DISP_ONLY ,CODE_AND_DISP };




enum FONT_ATTRIB {REGULAR, BOLD, INVERSE_REGULAR, INVERSE_BOLD};


#endif
